- name: Deploy Web Application
  hosts: vm1
  tasks:
    - name: Install Python dependencies for Kubernetes
      ansible.builtin.pip:
        name: kubernetes

    - name: Create Kubernetes namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: webapp

    - name: Deploy backend
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: backend
            namespace: webapp
          spec:
            replicas: 6
            selector:
              matchLabels:
                app: backend
            template:
              metadata:
                labels:
                  app: backend
              spec:
                containers:
                  - name: backend
                    image: <DOCKERHUB_USERNAME>/backend:latest
                    ports:
                      - containerPort: 80

    - name: Expose backend service
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: backend
            namespace: webapp
          spec:
            type: ClusterIP
            selector:
              app: backend
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Deploy frontend
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: frontend
            namespace: webapp
          spec:
            replicas: 4
            selector:
              matchLabels:
                app: frontend
            template:
              metadata:
                labels:
                  app: frontend
              spec:
                containers:
                  - name: frontend
                    image: <DOCKERHUB_USERNAME>/frontend:latest
                    ports:
                      - containerPort: 80

    - name: Expose frontend service
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: frontend
            namespace: webapp
          spec:
            type: NodePort
            selector:
              app: frontend
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80